name: Andrea Picco
##theme: minima

baseurl: '/trajectory_alignment'

##
## Parameters for WikiToJekyll
## Used by Rake:wikisub, Rake:wiki and wikiLinks generator plugin
###

wikiToJekyll:
    # your user Github Name
    user_name: apicco

    # your repository Name
    repository_name: trajectory_alignment

    deploy_remote: "origin"
    deploy_branch: "gh-pages"

    wiki_source: "_wiki"
    wiki_dest: "wiki"

    commit_and_push: false


