title: `trajalign` package
name: Andrea Picco
theme: minima
email: andrea.picco@unige.ch
description: The trajalign package aligns, in space and in time, the trajectories of diffraction limited objects, which are imaged in living cells with fluorescence microscopy, to precisely estimate their average dynamical properties.

baseurl: '/trajectory_alignment'
twitter_username: g_trevize

# Build settings

exclude:
    - Gemfile
    - Gemfile.lock
##
## Parameters for WikiToJekyll
## Used by Rake:wikisub, Rake:wiki and wikiLinks generator plugin
###

wikiToJekyll:
    # your user Github Name
    user_name: apicco

    # your repository Name
    repository_name: trajectory_alignment

    deploy_remote: "origin"
    deploy_branch: "gh-pages"

    wiki_source: "_wiki"
    wiki_dest: "wiki"

    commit_and_push: false


